### REGISTER Admin
POST http://localhost:7070/admins
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjNWM1NWUyOTc5ODAwNzBmNWY1MDc4Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5MDY4NTcwOCwiZXhwIjoxNjkwNzcyMTA4fQ.FOx6CouEiipKXqNBJ54orE-1Kw5hcsmlVdeMexmoWto
Content-Type: application/json

{
  "full_name": "admin",
  "username": "www",
  "password": "1234"
}

### LOGIN Admin
### bu username password super adminniki seed qoshilmagan shu yerdan login qilsangiz token beradi
POST http://localhost:7070/admins/login
Content-Type: application/json

{
  "username": "www",
  "password": "1234"
}

### GET all
#pagination: q=full_name filter={"full_name": ""}&sort={"full_name": 1}&limit=10&offset=0
#qolgan joylarda ham huddi shunday ishlaydi faqat maydon nomlari bowqaca bolishi kerak
###
GET http://localhost:7070/admins?sort={"username": 1}&limit=10&offset=0&q=a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjNTQ4ODE5ZWU2MTRlNzE5MmU3ZjIzIiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5MDY1MTI0OH0.Juzt916wY77a1SY6-NUWnYtgFT24YMbVXc-QRd_zrjk
### GET Admin
GET http://localhost:7070/admins/64c3eeb98e6b7e98dec7d4f6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjNWM1NWUyOTc5ODAwNzBmNWY1MDc4Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5MDY4NTcwOCwiZXhwIjoxNjkwNzcyMTA4fQ.FOx6CouEiipKXqNBJ54orE-1Kw5hcsmlVdeMexmoWto

### PATCH Me
PATCH http://localhost:7070/admins/me
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjNWM1NWUyOTc5ODAwNzBmNWY1MDc4Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5MDY4NTcwOCwiZXhwIjoxNjkwNzcyMTA4fQ.FOx6CouEiipKXqNBJ54orE-1Kw5hcsmlVdeMexmoWto
Content-Type: application/json

{
  "full_name": "admin"
}
###
# Patch Admin 
###
PATCH http://localhost:7070/admins/64c3eeb98e6b7e98dec7d4f6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjNWM1NWUyOTc5ODAwNzBmNWY1MDc4Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5MDY4NTcwOCwiZXhwIjoxNjkwNzcyMTA4fQ.FOx6CouEiipKXqNBJ54orE-1Kw5hcsmlVdeMexmoWto
Content-Type: application/json

{
  "full_name": "G`ishmat"
}

### DELETE Admin
DELETE http://localhost:7070/admins/64c3e578a7c259333fa33607
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRjNWM1NWUyOTc5ODAwNzBmNWY1MDc4Iiwicm9sZSI6InN1cGVyX2FkbWluIn0sImlhdCI6MTY5MDY4NTcwOCwiZXhwIjoxNjkwNzcyMTA4fQ.FOx6CouEiipKXqNBJ54orE-1Kw5hcsmlVdeMexmoWto